### ISSUE TITLE
filebot-watcher docker run command doesn't complete

### ISSUE THREAD

**Issue by AustinDoolittle** [filebot/plugins#13]
I am attempting to install the filebot-watcher docker instance. I am using the following command:
```
docker run -it -v /apps/docker/:/volume1 \
-v data:/data rednoah/filebot:watcher \
/volume1/plex/data --output /volume1/deluge/data/completed
```

when I do this, I get the following output:
```
Setting up watches.
Watches established.
```
After these two lines of output, the command just sits and does nothing further.

Environment:
OS: Ubuntu 16.04
Docker Version output:
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
``` 

Any and all help is appreciated!

**Comment by rednoah** [comment]
Well, yes. It's gonna be sitting there, watching, waiting for new files to appear, and the process them, and then go back to sitting there and watching, and so on. It's not supposed to quit, unless you quit it.

If you want a command to run (or wait and do nothing) in background, then you can use `&` or `screen`.

**Comment by AustinDoolittle** [comment]
This is the output from the docker run command. Shouldn't this output and all watcher processes be contained within the docker container that the command is starting up?

**Comment by AustinDoolittle** [comment]
Welp, I probably should've read the docker documentation before posting this. I didn't realized that the `-it` flag attaches the current shell to the docker output. Thanks for entertaining my idiocy!

**Comment by rednoah** [comment]
Feel free to explain the solution for the next guy. ;)

**Comment by AustinDoolittle** [comment]
I'm not entirely sure that I solved it, but it appears to be working. I ssh into the host machine and run the following command:
```
docker run --restart=always  \
-v /apps/docker/plex/data/:/out \
-v /apps/docker/deluge/data/completed/:/completed \
rednoah/filebot:watcher /completed --output /out \
--def movieFormat="M:/Movies/{ny}/{fn}" seriesFormat="S:/Shows/{n}/{fn}"
```

I still get the output described above and the shell still blocks indefinitely. However, when I disconnect, reconnect, and run `docker ps`, the container is listed as running. Possibly you may be able to shed some light on this?
