### ISSUE TITLE
TheTVDB.com Moved to http://platypus.thetvdb.com

### ISSUE THREAD

**Issue by HeedfulCrayon** [filebot/plugins#16]
Filebot is unable to grab TV DB info because TheTVDB.com is down

**Comment by rednoah** [comment]
Temporary down, sure. Permanently moved, doubtful. Do you have any official statement backing that up?

FileBot uses the official API endpoint:
https://api.thetvdb.com/swagger

**Comment by HeedfulCrayon** [comment]
You are correct, it has not moved permanently, it is just flaky apparently
