### ISSUE TITLE
Yum Repo URL gives 404

### ISSUE THREAD

**Issue by gekoraus** [filebot/plugins#18]
Hi,
unfortunately the rpm repo (https://get.filebot.net/rpm/main/x86_64) is gone missing. It just gives a 404 not found.
Thanks in advance for fixing the issue!

**Comment by rednoah** [comment]
The `x86_64` repository will be enabled with `FileBot 4.9.2`. `FileBot 4.9.1` is available in the `noarch` repository (https://get.filebot.net/rpm/universal-jdk8/noarch) but there are a lot of users that find it hard to satisfy all the dependencies.

On non-Debian platforms, the easiest way to get things up and running is `snap`:
https://www.filebot.net/forums/viewtopic.php?t=5984

**Comment by gekoraus** [comment]
Thanks! After changing the URL and installing JavaFX everything is working as expected again.
