### ISSUE TITLE
deb.sh installer uses incorrect `gnupg-curl` package name in Ubuntu

### ISSUE THREAD

**Issue by themacguffinman** [filebot/plugins#19]
The `deb.sh` installer script tries to install the `gnupg-curl` package which doesn't seem to exist in Ubuntu 20.10:

https://github.com/filebot/plugins/blob/3fa38d6685a7ed02fe673bc7f61fe6d49d43c892/installer/deb.sh#L15-L16

The script should be installing the `curl` package instead (Debian also seems to have a `curl` package [since Jessie](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=curl)).

**Comment by rednoah** [comment]
This line lists all the packages that might be required. On `20.10` specifically, some of them might not be required, or might not exist. That's ok. This line will install what it can, and assume that the rest works by default.

Notably, `gnupg-curl` is not a replacement for `curl`, but it is something that is required for `1. Import signing keys`, at least on older Ubuntu versions.
