### ISSUE TITLE
installer/deb.sh error in source.list

### ISSUE THREAD

**Issue by schmittyd** [filebot/plugins#23]
`W: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'https://get.filebot.net/deb universal InRelease' does not seem to provide it (sources.list entry misspelt?)`

**Comment by rednoah** [comment]
Please try again with https://github.com/filebot/plugins/commit/dd09ecacdb928bbfd27fc7cd4c31a7274d8cf218
