### ISSUE TITLE
break out the docker files into separate repos?

### ISSUE THREAD

**Issue by RXWatcher** [filebot/plugins#5]
I want to fork these and modify them a bit so they automatically check/pull the latest version of filebot on restart. I dont want to fork your entire plugins repo to do this as it seems like overkill and not very clean.

I would appreciate it if you could create one for each docker image...filebot, filebot-node and filebot-watcher.

Thank you!

**Comment by rednoah** [comment]
That's true. Docker seems to require a repository for each docker file.

**Comment by rednoah** [comment]
Do you want to modify it image though? How come you don't use the latest existing image? That's always gonna be using the latest version of FileBot.

**Comment by RXWatcher** [comment]
I can do that but I would need to use something like this to check for updated images and automatically update.  https://github.com/v2tec/watchtower   That will work for me and I can just handle it that way. 

I havent even put your images to use yet, It was just something I thought would save having to check/pull new images for every update to filebot.

**Comment by RXWatcher** [comment]
Now that I think of it, watchtower might be a better way of handling it as it would happen without needing to restart the container.

I'll close this. Thanks for your time.

**Comment by rednoah** [comment]
I'm not sure if I'd update the images mid-flight, but it's certainly possible. Doesn't it boil down to just calling `docker pull <image>` once per day? Or maybe just on startup?
