### ISSUE TITLE
Option to change AMC Commands executet by watcher docker

### ISSUE THREAD

**Issue by ghost** [filebot/plugins#7]
Hi Rednoah, 

i'd love to use your slim docker to realise my automation further.
IS there a option to define more arguments executed by de watcher docker ?

Thanks!

**Comment by rednoah** [comment]
What arguments would you like? You can pass any `filebot` option to the `filebot-watcher` script.

**Comment by ghost** [comment]
and how would i pass those arguments ?
can you post a example ?

**Comment by rednoah** [comment]
Here's what the `filebot-watcher` script does:
```
filebot -script fn:amc ... "$@"
```

Any arguments you pass to the `filebot-watcher` script will be passed along to the amc call, so you could add anything that filebot/amc would accept.

So this:
```
filebot -script fn:amc <filebot arguments>
```
is the same as this:
```
docker run ... rednoah/filebot:watcher <filebot arguments>
```

**Comment by ghost** [comment]
great !

**Comment by ghost** [comment]
Okay.
tried it - 
```
Setting up watches.
Watches established.
```
is everything i get


this is my code:
```
#!/bin/bash

QUOTE_FIXER='replaceAll(/[\`\u00b4\u2018\u2019\u02bb]/, "'"'"'").replaceAll(/[\u201c\u201d]/, '"'"'""'"'"')'
# Customize the renaming format here. For info on formatting: https://www.filebot.net/naming.html

# Music/Eric Clapton/From the Cradle/05 - It Hurts Me Too.mp3
MUSIC_FORMAT="Musik/{n.$QUOTE_FIXER}/{album.$QUOTE_FIXER}/{media.TrackPosition.pad(2)} - {t.$QUOTE_FIXER}"

# Movies/Fight Club(1990)/Fight Club(1990).mkv
MOVIE_FORMAT="Filme/{n.$QUOTE_FIXER} ({y})/{n.$QUOTE_FIXER} ({y}){' CD'+pi}"

# TV Shows/Game of Thrones/Season 05/Game of Thrones - S05E08 - Hardhome.mp4
# TV Shows/Game of Thrones/Special/Game of Thrones - S00E11 - A Day in the Life.mp4
SERIES_FORMAT="Serien/{n}/{episode.special ? 'Special' : 'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2) : s00e00} - {t.${QUOTE_FIXER}.replaceAll(/[!?.]+$/).replacePart(', Part $1')}{'.'+lang}"

# See http://www.filebot.net/forums/viewtopic.php?t=215 for details on amc
docker run -it -v /media/Daten/Medien:/volume1/output -v /media/Daten/Medien/Downloads:/volume1/input -e USER_ID=1000 -e GROUP_ID=1000 rednoah/filebot:watcher /volume1/input --output /volume1/output -no-xattr --log-file /output/FileBot.log --action move --conflict override --lang de\
  -non-strict --def ut_dir=/input ut_kind=multi music=y deleteAfterExtract=y clean=y skipExtract=y  emby=192.168.0.2:secret\
  movieFormat="$MOVIE_FORMAT" musicFormat="$MUSIC_FORMAT" seriesFormat="$SERIES_FORMAT"

```


when i go into the container and check for files in /volume1/input/
there are files downloading and extracting.
after extracting is done (file.s01.e01.mkv) nothing happens
no further log messages

**Comment by ghost** [comment]
okay. problem solved by putting the file i want to sort putting in root.
can u pls enhance the watcher script to dive into folders?
maybe depth 2 or 3

**Comment by ghost** [comment]
now i get this error message:
```
Argument[0]: /volume1/input
Illegal usage: use either script parameters [dir:/volume1/input, kind:multi] or file arguments [/volume1/input] but not both
Failure (°_°)

```

**Comment by ghost** [comment]
```
#!/bin/bash

QUOTE_FIXER='replaceAll(/[\`\u00b4\u2018\u2019\u02bb]/, "'"'"'").replaceAll(/[\u201c\u201d]/, '"'"'""'"'"')'
# Customize the renaming format here. For info on formatting: https://www.filebot.net/naming.html

# Music/Eric Clapton/From the Cradle/05 - It Hurts Me Too.mp3
MUSIC_FORMAT="Musik/{n.$QUOTE_FIXER}/{album.$QUOTE_FIXER}/{media.TrackPosition.pad(2)} - {t.$QUOTE_FIXER}"

# Movies/Fight Club(1990)/Fight Club(1990).mkv
MOVIE_FORMAT="Filme/{n.$QUOTE_FIXER} ({y})/{n.$QUOTE_FIXER} ({y}){' CD'+pi}"

# TV Shows/Game of Thrones/Season 05/Game of Thrones - S05E08 - Hardhome.mp4
# TV Shows/Game of Thrones/Special/Game of Thrones - S00E11 - A Day in the Life.mp4
SERIES_FORMAT="Serien/{n}/{episode.special ? 'Special' : 'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2) : s00e00} - {t.${QUOTE_FIXER}.replaceAll(/[!?.]+$/).replacePart(', Part $1')}{'.'+lang}"

# See http://www.filebot.net/forums/viewtopic.php?t=215 for details on amc
docker run -it -v /media/Daten/Medien:/volume1/output -v /media/Daten/Medien/Downloads:/volume1/input -e USER_ID=1000 -e GROUP_ID=1000 rednoah/filebot:watcher /volume1/input --output /volume1/output --log-file /volume1/output/FileBot.lo$
  -non-strict --def music=y deleteAfterExtract=y clean=y skipExtract=y  emby=192.168.0.2:<secret>\
  movieFormat="$MOVIE_FORMAT" musicFormat="$MUSIC_FORMAT" seriesFormat="$SERIES_FORMAT" &

```

removing UT commands worked :)
if you merge my request i'd be completely happy!

**Comment by rednoah** [comment]
Recursive watching of folders doesn't work reliably. You should only watch the folder where completed downloads are moved, so any new file or new folder that appears will be processed. I don't really understand why you'd need to watch folders recursively.

**Comment by ghost** [comment]
i think i understand. 
i modifed my jdownloader settings. extracted file will be moved to a certain folder.
but it seems the 2 secondes is to short...
it recognizes the folder wenn moved manually
but moved by jdownloaded automatism it seems to take longer

i get this message:
`Modified: /volume1/input/DMWLD`
and nothing else happens

**Comment by rednoah** [comment]
If you move files on the same filesystem, it will never take longer than a few nanoseconds. 

If it takes seconds you're copying files to a different filesystem, and you probably shouldn't do that. Plus, watching will not work correctly and probably fire off early and process partially copied files. ;)

**Comment by ghost** [comment]
i know. but jdownloader is not able to "move after extraction". or i didnt find a option for it.
it only extracts to a folder.

**Comment by rednoah** [comment]
If you're using JD, why are you not using the official JD integration?
https://www.filebot.net/forums/viewtopic.php?f=4&t=3478

`filebot-watcher` won't work if files don't appear instantly, so it won't work well for files that are slowly copied, or slowly extracted.

**Comment by ghost** [comment]
the problem is, i dockerized everything to have my system stable.
i now used your postprocess.sh to move the files to the watched folder after extraction is complete.

maybe i integrate filebot into my jdownloader docker. but for now this process works :)
